# Generated by Django 4.2.23 on 2025-09-18 18:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='entry',
            new_name='entry_text',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='user',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sih_app.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
