# Generated by Django 5.2.6 on 2025-09-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0004_alter_journalentry_student_counsellorslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_update_interval', models.PositiveIntegerField(default=3600, help_text='Quote update interval in seconds')),
            ],
        ),
    ]
