# Generated by Django 5.2.6 on 2025-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sih_app', '0008_chatroom_chatroommembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
